# Generated by Django 4.1.1 on 2023-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_line1",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="pincode",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(default=None, upload_to="profile_pictures"),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
