# Generated by Django 4.1.1 on 2023-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_address_line1_user_city_user_pincode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address_line1",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="pincode",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, upload_to="profile_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
